\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/SQLFiles/uploadTables.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Business/business0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Category/categories0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Category/categories1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Attribute/attributes0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Attribute/attributes1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Attribute/attributes2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Attribute/attributes3.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Hour/hours0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Hour/hours1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Hour/hours2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin3.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin4.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin5.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin6.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin7.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin8.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin9.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin10.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin11.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin12.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin13.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin14.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin15.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin16.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin17.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin18.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin19.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin20.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin21.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin22.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin23.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin24.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin25.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin26.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin27.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin28.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin29.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin30.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin31.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin32.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin33.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin34.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin35.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin36.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin37.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin38.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin39.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin40.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin41.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin42.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin43.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin44.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin45.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin46.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin47.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin48.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin49.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin50.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin51.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin52.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin53.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin54.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin55.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin56.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin57.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin58.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin59.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin60.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin61.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin62.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin63.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin64.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin65.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin66.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin67.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin68.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Checkin/checkin69.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/User/users0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/User/users1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/User/users2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/User/users3.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/User/users4.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/User/users5.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends3.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends4.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends5.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends6.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends7.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends8.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends9.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends10.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends11.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends12.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends13.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends14.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends15.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends16.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends17.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends18.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends19.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends20.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends21.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends22.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends23.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends24.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends25.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends26.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends27.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends28.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends29.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends30.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends31.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends32.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends33.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends34.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends35.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends36.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends37.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends38.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends39.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends40.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends41.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends42.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends43.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends44.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends45.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends46.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends47.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends48.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends49.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends50.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends51.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends52.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends53.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends54.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends55.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends56.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends57.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends58.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends59.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends60.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends61.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends62.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends63.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends64.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends65.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends66.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends67.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends68.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends69.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends70.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends71.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends72.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends73.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends74.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends75.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends76.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends77.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends78.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends79.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends80.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends81.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends82.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends83.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends84.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends85.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends86.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends87.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends88.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends89.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends90.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends91.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends92.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends93.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends94.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends95.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends96.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends97.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends98.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends99.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends100.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends101.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends102.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends103.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends104.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends105.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends106.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends107.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends108.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends109.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends110.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends111.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends112.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends113.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends114.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends115.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends116.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends117.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends118.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends119.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends120.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends121.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends122.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends123.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends124.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends125.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends126.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends127.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends128.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends129.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends130.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends131.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends132.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends133.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends134.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends135.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends136.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends137.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends138.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends139.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends140.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends141.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends142.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends143.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends144.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends145.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends146.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends147.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends148.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends149.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends150.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends151.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends152.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends153.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends154.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends155.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends156.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends157.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends158.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends159.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends160.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends161.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends162.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends163.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends164.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends165.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends166.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends167.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends168.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends169.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends170.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends171.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends172.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends173.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends174.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends175.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends176.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends177.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends178.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends179.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends180.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends181.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends182.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends183.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends184.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends185.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends186.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends187.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends188.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends189.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends190.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends191.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends192.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends193.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends194.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends195.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends196.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends197.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends198.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends199.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends200.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends201.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends202.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends203.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends204.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends205.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends206.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends207.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends208.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends209.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends210.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends211.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends212.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends213.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends214.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends215.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends216.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends217.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends218.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends219.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends220.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends221.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends222.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends223.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends224.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends225.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends226.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends227.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends228.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends229.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends230.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends231.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends232.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends233.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends234.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends235.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends236.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends237.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends238.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends239.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends240.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends241.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends242.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends243.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends244.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends245.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends246.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends247.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends248.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends249.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends250.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends251.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends252.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends253.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends254.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends255.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends256.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends257.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends258.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends259.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends260.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends261.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends262.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends263.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends264.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends265.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends266.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends267.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends268.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends269.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends270.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends271.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends272.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends273.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends274.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends275.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends276.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends277.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends278.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends279.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends280.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends281.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends282.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends283.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends284.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends285.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends286.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends287.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends288.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends289.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends290.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends291.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends292.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends293.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends294.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends295.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends296.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends297.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends298.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends299.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends300.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends301.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends302.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends303.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends304.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends305.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends306.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends307.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends308.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends309.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends310.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends311.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends312.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends313.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends314.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends315.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends316.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends317.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends318.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends319.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends320.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends321.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends322.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends323.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends324.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends325.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends326.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends327.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends328.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends329.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends330.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends331.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends332.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends333.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends334.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends335.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends336.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends337.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends338.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Friend/friends339.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Tip/tips0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Tip/tips1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Tip/tips2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Tip/tips3.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review3.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review4.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review5.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review6.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review7.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review8.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review9.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review10.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review11.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review12.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review13.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review14.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review15.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review16.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review17.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review18.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review19.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review20.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review21.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review22.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review23.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review24.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/ParsedData/Review/Review25.sql
