\i C:/Users/pauld/OneDrive/Desktop/415-project/SQLFiles/uploadTables.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review0.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review1.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review2.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review3.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review4.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review5.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review6.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review7.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review8.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review9.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review10.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review11.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review12.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review13.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review14.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review15.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review16.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review17.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review18.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review19.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review20.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review21.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review22.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review23.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review24.sql
\i C:/Users/pauld/OneDrive/Desktop/415-project/ParsedData/Review/Review25.sql
